### ISSUE TITLE
Java 16+ not supported (Reflection error)

### ISSUE THREAD

**Issue by allentiak** [apitestbase/apitestbase#1]
When running the application under Java 16+, I get a Reflection error.
Running the same command under Java 11 works fine.

```
% java -version                                             
openjdk version "18-ea" 2022-03-22
OpenJDK Runtime Environment (build 18-ea+36-Debian-1)
OpenJDK 64-Bit Server VM (build 18-ea+36-Debian-1, mixed mode, sharing)

% java -Djava.net.useSystemProxies=true -jar apitestbase-0.19.0.jar server config.yml
INFO  [2022-04-12 23:34:03,325] org.eclipse.jetty.util.log: Logging initialized @1434ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [2022-04-12 23:34:03,405] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2022-04-12 23:34:03,406] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2022-04-12 23:34:03,406] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: ui for path /ui/*
INFO  [2022-04-12 23:34:03,407] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: lib for path /ui/lib/*
INFO  [2022-04-12 23:34:03,407] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: mockserver for path /ui/mockserver/*
INFO  [2022-04-12 23:34:03,407] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: common for path /ui/common/*
INFO  [2022-04-12 23:34:04,240] org.eclipse.jetty.server.Server: jetty-9.4.43.v20210629; built: 2021-06-30T11:07:22.254Z; git: 526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8; jvm 18-ea+36-Debian-1
INFO  [2022-04-12 23:34:04,255] org.eclipse.jetty.server.handler.ContextHandler: Started o.e.j.s.ServletContextHandler@5db948c9{/__admin,null,AVAILABLE}
INFO  [2022-04-12 23:34:04,258] org.eclipse.jetty.server.handler.ContextHandler.ROOT: RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
INFO  [2022-04-12 23:34:04,258] org.eclipse.jetty.server.handler.ContextHandler: Started o.e.j.s.ServletContextHandler@6a2d867d{/,null,AVAILABLE}
INFO  [2022-04-12 23:34:04,268] org.eclipse.jetty.server.AbstractConnector: Started NetworkTrafficServerConnector@1df5c7e3{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:8092}
INFO  [2022-04-12 23:34:04,271] org.eclipse.jetty.util.ssl.SslContextFactory: x509=X509@13250132(wiremock,h=[tom akehurst],a=[],w=[]) for Server@40d848f9[provider=Conscrypt,keyStore=null,trustStore=null]
INFO  [2022-04-12 23:34:04,271] org.eclipse.jetty.util.ssl.SslContextFactory: Unable to get KeyManagerFactory instance for algorithm [SunX509] on provider [Conscrypt], using default
INFO  [2022-04-12 23:34:04,279] org.eclipse.jetty.util.ssl.SslContextFactory: Unable to get SSLContext instance for protocol [TLS] on provider [Conscrypt], using default
INFO  [2022-04-12 23:34:04,312] org.eclipse.jetty.server.AbstractConnector: Started NetworkTrafficServerConnector@1961d75a{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8093}
INFO  [2022-04-12 23:34:04,313] org.eclipse.jetty.server.Server: Started @2423ms
INFO  [2022-04-12 23:34:04,882] org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean: Creating Service {http://ws.apitestbase.io/}ArticleSOAPService from class io.apitestbase.ws.ArticleSOAP
javax.xml.ws.WebServiceException: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at org.apache.cxf.jaxws.EndpointImpl.doPublish(EndpointImpl.java:375)
	at org.apache.cxf.jaxws.EndpointImpl.publish(EndpointImpl.java:255)
	at com.roskart.dropwizard.jaxws.JAXWSEnvironment.publishEndpoint(JAXWSEnvironment.java:113)
	at com.roskart.dropwizard.jaxws.JAXWSBundle.publishEndpoint(JAXWSBundle.java:85)
	at io.apitestbase.APITestBaseApplication.createSampleResources(APITestBaseApplication.java:328)
	at io.apitestbase.APITestBaseApplication.run(APITestBaseApplication.java:147)
	at io.apitestbase.APITestBaseApplication.run(APITestBaseApplication.java:54)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at io.apitestbase.APITestBaseApplication.main(APITestBaseApplication.java:58)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:294)
	at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:66)
	at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:57)
	at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:99)
	at com.sun.xml.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.optimize(Accessor.java:374)
	at com.sun.xml.bind.v2.runtime.property.SingleElementLeafProperty.<init>(SingleElementLeafProperty.java:62)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:99)
	at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:150)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:493)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:512)
	at com.sun.xml.bind.v2.runtime.property.SingleElementNodeProperty.<init>(SingleElementNodeProperty.java:75)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
	at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:99)
	at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:150)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:493)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:310)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1142)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:144)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:251)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:240)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:363)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:345)
	at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:343)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.cxf.common.jaxb.JAXBContextCache.createContext(JAXBContextCache.java:343)
	at org.apache.cxf.common.jaxb.JAXBContextCache.getCachedContextAndSchemas(JAXBContextCache.java:245)
	at org.apache.cxf.jaxb.JAXBDataBinding.createJAXBContextAndSchemas(JAXBDataBinding.java:500)
	at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:359)
	at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:87)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromClass(ReflectionServiceFactoryBean.java:469)
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.buildServiceFromClass(JaxWsServiceFactoryBean.java:693)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:529)
	at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:262)
	at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:199)
	at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:103)
	at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168)
	at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211)
	at org.apache.cxf.jaxws.EndpointImpl.getServer(EndpointImpl.java:460)
	at org.apache.cxf.jaxws.EndpointImpl.doPublish(EndpointImpl.java:338)
	... 11 more
ERROR [2022-04-12 23:34:05,074] com.sun.xml.bind.v2.runtime.reflect.opt.Injector: null
! java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
! at java.base/java.lang.Class.getMethod(Class.java:2259)
! at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:170)
! at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:166)
! at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
! ... 58 common frames omitted
! Causing: java.security.PrivilegedActionException: null
! at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
! at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:166)
! at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:51)
! at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:99)
! at com.sun.xml.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.optimize(Accessor.java:374)
! at com.sun.xml.bind.v2.runtime.property.SingleElementLeafProperty.<init>(SingleElementLeafProperty.java:62)
! at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
! at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
! at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
! at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:99)
! at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:150)
! at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:493)
! at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:512)
! at com.sun.xml.bind.v2.runtime.property.SingleElementNodeProperty.<init>(SingleElementNodeProperty.java:75)
! at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
! at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
! at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
! at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:99)
! at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:150)
! at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:493)
! at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:310)
! at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
! at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1142)
! at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:144)
! at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
! at java.base/java.lang.reflect.Method.invoke(Method.java:577)
! at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:251)
! at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:240)
! at javax.xml.bind.ContextFinder.find(ContextFinder.java:363)
! at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
! at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:345)
! at org.apache.cxf.common.jaxb.JAXBContextCache$2.run(JAXBContextCache.java:343)
! at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
! at org.apache.cxf.common.jaxb.JAXBContextCache.createContext(JAXBContextCache.java:343)
! at org.apache.cxf.common.jaxb.JAXBContextCache.getCachedContextAndSchemas(JAXBContextCache.java:245)
! at org.apache.cxf.jaxb.JAXBDataBinding.createJAXBContextAndSchemas(JAXBDataBinding.java:500)
! at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:359)
! at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:87)
! at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromClass(ReflectionServiceFactoryBean.java:469)
! at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.buildServiceFromClass(JaxWsServiceFactoryBean.java:693)
! at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:529)
! at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:262)
! at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:199)
! at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:103)
! at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:168)
! at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:211)
! at org.apache.cxf.jaxws.EndpointImpl.getServer(EndpointImpl.java:460)
! at org.apache.cxf.jaxws.EndpointImpl.doPublish(EndpointImpl.java:338)
! at org.apache.cxf.jaxws.EndpointImpl.publish(EndpointImpl.java:255)
! at com.roskart.dropwizard.jaxws.JAXWSEnvironment.publishEndpoint(JAXWSEnvironment.java:113)
! at com.roskart.dropwizard.jaxws.JAXWSBundle.publishEndpoint(JAXWSBundle.java:85)
! at io.apitestbase.APITestBaseApplication.createSampleResources(APITestBaseApplication.java:328)
! at io.apitestbase.APITestBaseApplication.run(APITestBaseApplication.java:147)
! at io.apitestbase.APITestBaseApplication.run(APITestBaseApplication.java:54)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at io.apitestbase.APITestBaseApplication.main(APITestBaseApplication.java:58)
```

**Comment by zheng-wang** [comment]
Thanks for identifying this issue. I'll fix it in the next release.

In the meantime as a workaround you can try below steps to run ATB 0.19.0 with JDK 16+ (I tested with JDK 18):
1. Download 0.19.0 source code https://github.com/apitestbase/apitestbase/archive/refs/tags/v0.19.0.zip.
2. Unzip the source code, replace apitestbase-core-server/pom.xml and apitestbase-bom/pom.xml with those in the 
[pom files.zip](https://github.com/apitestbase/apitestbase/files/8481236/pom.files.zip).
3. Run `mvn clean package -P prod` to rebuild the 0.19.0 dist.
4. Run the new dist with JDK 16+.

Please refer to https://apitestbase.io/docs/en/build-api-test-base-by-yourself for the context information.

**Comment by allentiak** [comment]
@zheng-wang Thank you for your quick reply!
And thanks for the workaround.

**Comment by zheng-wang** [comment]
@allentiak welcome. Hopefully issue has been resolved.
